version: '3.8'

services:
  xrdp_service:
    image: ubuntu:latest
    container_name: xrdp-container
    environment:
      DEBIAN_FRONTEND: noninteractive
      RDP_PORT: 3389
      RDP_USER: "user"
      RDP_PASSWORD: "@run#123"
    ports:
      - "3389:3389"
    volumes:
      - xrdp_logs:/var/log/supervisor
    command: >
      bash -c "
      apt-get update && 
      apt-get install -y xrdp xfce4 xfce4-goodies supervisor net-tools &&
      apt-get clean &&
      rm -rf /var/lib/apt/lists/* &&
      
      # Configure XRDP port and user
      adduser xrdp ssl-cert &&
      sed -i 's/3389/${RDP_PORT}/g' /etc/xrdp/xrdp.ini &&
      echo 'startxfce4' > /etc/skel/.xsession &&
      
      # Configure Supervisor to manage XRDP services
      mkdir -p /var/log/supervisor &&
      echo '[supervisord]' > /etc/supervisor/conf.d/supervisord.conf &&
      echo 'nodaemon=true' >> /etc/supervisor/conf.d/supervisord.conf &&
      echo '[program:xrdp-sesman]' >> /etc/supervisor/conf.d/supervisord.conf &&
      echo 'command=/usr/sbin/xrdp-sesman --nodaemon' >> /etc/supervisor/conf.d/supervisord.conf &&
      echo 'stdout_logfile=/var/log/supervisor/xrdp-sesman.log' >> /etc/supervisor/conf.d/supervisord.conf &&
      echo 'stderr_logfile=/var/log/supervisor/xrdp-sesman.err' >> /etc/supervisor/conf.d/supervisord.conf &&
      echo '[program:xrdp]' >> /etc/supervisor/conf.d/supervisord.conf &&
      echo 'command=/usr/sbin/xrdp --nodaemon' >> /etc/supervisor/conf.d/supervisord.conf &&
      echo 'stdout_logfile=/var/log/supervisor/xrdp.log' >> /etc/supervisor/conf.d/supervisord.conf &&
      echo 'stderr_logfile=/var/log/supervisor/xrdp.err' >> /etc/supervisor/conf.d/supervisord.conf &&
      
      # Set password for user
      echo '${RDP_USER}:${RDP_PASSWORD}' | chpasswd &&
      
      # Start Supervisor to manage xrdp and xrdp-sesman
      /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
      "

volumes:
  xrdp_logs:
